name: Format

on:
  push:
    branches: main

permissions:
  contents: write

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: "."
          extensions: "h, cpp"
          clangFormatVersion: 16
          inplace: true

      - name: Run Prettier
        uses: actionsx/prettier@v3
        with:
          args: --write "${{ github.workspace }}/*.json"

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: "ci: formatting"
          committer_name: maintenance
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
