name: Test Build

on:
  push:
    branches: main
    paths:
      - "include/**"
      - "src/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".github/workflows/testbuild.yml"
  workflow_dispatch:

jobs:
  test-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        preset:
          - debug
          - release
        compiler:
          - msvc
          - clang-cl
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Setup MSVC prompt
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          toolset: 14.37

      - name: Build
        run: |
          cmake --preset=build-${{ matrix.preset }}-${{ matrix.compiler }}
          cmake --build --preset=${{ matrix.preset }}-${{ matrix.compiler }}
